### ISSUE TITLE
php 7.3.0b3 compatibility for php-redis

### ISSUE THREAD

**Issue by PhilETaylor** [php-earth/alpine#8]
Forked from https://github.com/phpredis/phpredis/issues/1397#issuecomment-418706017

Firstly, not sure if this is the right place or if this is an Apline issue, but... hey ho.

Alpine Linux has PHP 7.3 beta3 available, and 4.1.1 of [php7.3-redis](https://repos.php.earth/alpine/v3.8/x86_64/php7.3-redis-4.1.1-r0.apk)

I'm using docker to build a container with PHP 7.3 beta3 with the above. 

On installation I get the error below

On running PHP at the command line I get the same error below

### Expected behaviour

No errors :) 

### Actual behaviour

Error:

"**_zval_ptr_dtor: symbol not found**"

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/lib/php/7.3/modules/redis (Error loading shared library /usr/lib/php/7.3/modules/redis: No such file or directory), /usr/lib/php/7.3/modules/redis.so (Error relocating /usr/lib/php/7.3/modules/redis.so: _zval_ptr_dtor: symbol not found)) in Unknown on line 0
```

### I'm seeing this behaviour on
- OS: Alpine:latest
- Redis: n/a
- PHP: 7.3.0b3
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script

DockerFile:

```
FROM alpine:latest

ADD https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
RUN apk update \
    && echo "https://repos.php.earth/alpine/v3.8" >> /etc/apk/repositories \
    && apk add --no-cache supervisor composer git openssh ca-certificates curl wget zlib-dev procps \
    php7.3              \
    php7.3-dev          \
    php7.3-fpm          \
    php7.3-curl         \
    php7.3-zip          \
    php7.3-mbstring     \
    php7.3-pcntl        \
    php7.3-posix        \
    php7.3-iconv        \
    php7.3-intl         \
    php7.3-pdo_mysql    \
    php7.3-tokenizer    \
    php7.3-dom          \
    php7.3-redis        \
    php7.3-xml          \
    php7.3-simplexml    \
    php7.3-json         \
    php7.3-sodium       \
    php7.3-opcache      \
    php7.3-shmop        \
    php7.3-xmlwriter    \
    php7.3-common

# <snip>

EXPOSE 9000

CMD ["php-fpm"]

```

**Comment by Maikuolan** [comment]
@petk : This issue possibly might become not relevant anymore after #9 is addressed, due to that this issue here (#8) concerns PHP 7.3.0 beta3 (whereas #9 concerns compiling a new build for PHP 7.3.0 RC2). Probably, I think, #9 should be dealt with first (when there's time for it), and then after, we can confirm whether this issue (#8) still persists or not.

**Comment by petk** [comment]
I think this has been fixed upstream then... Thanks for reporting. Since it's resolved closing this one. Cheers.

**Comment by PhilETaylor** [comment]
This is still a problem today as evidenced by the build test below.

```
Step 1/5 : FROM alpine:latest
 ---> 196d12cf6ab1
Step 2/5 : ADD https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
Downloading     800B/800B

 ---> 0dc9b16e5439
Step 3/5 : RUN apk update     && echo "https://repos.php.earth/alpine/v3.8" >> /etc/apk/repositories     && apk add --no-cache supervisor composer git openssh ca-certificates curl wget zlib-dev procps     php7.3                  php7.3-dev              php7.3-fpm              php7.3-curl             php7.3-zip              php7.3-mbstring         php7.3-pcntl            php7.3-posix            php7.3-iconv            php7.3-intl             php7.3-pdo_mysql        php7.3-tokenizer        php7.3-dom              php7.3-redis            php7.3-xml              php7.3-simplexml        php7.3-json             php7.3-sodium           php7.3-opcache          php7.3-shmop            php7.3-xmlwriter        php7.3-common
 ---> Running in 4084c5088879
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.1-30-g4b616938a6 [http://dl-cdn.alpinelinux.org/alpine/v3.8/main]
v3.8.1-28-g1d8df16b35 [http://dl-cdn.alpinelinux.org/alpine/v3.8/community]
OK: 9539 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
fetch https://repos.php.earth/alpine/v3.8/x86_64/APKINDEX.tar.gz
(1/95) Installing ca-certificates (20171114-r3)
(2/95) Installing composer (1.7.2-r100)
(3/95) Installing nghttp2-libs (1.32.0-r0)
(4/95) Installing libssh2 (1.8.0-r3)
(5/95) Installing libcurl (7.61.1-r0)
(6/95) Installing curl (7.61.1-r0)
(7/95) Installing expat (2.2.5-r0)
(8/95) Installing pcre2 (10.31-r0)
(9/95) Installing git (2.18.0-r0)
(10/95) Installing openssh-keygen (7.7_p1-r3)
(11/95) Installing openssh-client (7.7_p1-r3)
(12/95) Installing openssh-sftp-server (7.7_p1-r3)
(13/95) Installing openssh-server-common (7.7_p1-r3)
(14/95) Installing openssh-server (7.7_p1-r3)
(15/95) Installing openssh (7.7_p1-r3)
(16/95) Installing php7.3-common (7.3.0-r5)
(17/95) Installing php7.3-zlib (7.3.0-r5)
(18/95) Installing php7.3-phar (7.3.0-r5)
Executing php7.3-phar-7.3.0-r5.post-install
(19/95) Installing php7.3-json (7.3.0-r5)
(20/95) Installing php7.3-mbstring (7.3.0-r5)
(21/95) Installing php7.3-openssl (7.3.0-r5)
(22/95) Installing libzip (1.5.1-r1)
(23/95) Installing php7.3-zip (7.3.0-r5)
(24/95) Installing php7.3-composer (1.0.0-r0)
(25/95) Installing argon2-libs (20171227-r1)
(26/95) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(27/95) Installing ncurses-terminfo (6.1_p20180818-r1)
(28/95) Installing ncurses-libs (6.1_p20180818-r1)
(29/95) Installing libedit (20170329.3.1-r3)
(30/95) Installing libxml2 (2.9.8-r0)
(31/95) Installing php7.3 (7.3.0-r5)
Executing php7.3-7.3.0-r5.post-install
(32/95) Installing php7.3-curl (7.3.0-r5)
(33/95) Installing php7.3-xml (7.3.0-r5)
(34/95) Installing php7.3-pear (7.3.0-r5)
Executing php7.3-pear-7.3.0-r5.post-install
(35/95) Installing m4 (1.4.18-r1)
(36/95) Installing libbz2 (1.0.6-r6)
(37/95) Installing perl (5.26.2-r1)
(38/95) Installing autoconf (2.69-r2)
(39/95) Installing pkgconf (1.5.3-r0)
(40/95) Installing ncurses-dev (6.1_p20180818-r1)
(41/95) Installing libedit-dev (20170329.3.1-r3)
(42/95) Installing zlib-dev (1.2.11-r1)
(43/95) Installing libpcre2-16 (10.31-r0)
(44/95) Installing libpcre2-32 (10.31-r0)
(45/95) Installing pcre2-dev (10.31-r0)
(46/95) Installing libgcc (6.4.0-r9)
(47/95) Installing libstdc++ (6.4.0-r9)
(48/95) Installing re2c (1.0.2-r0)
(49/95) Installing libmagic (5.32-r0)
(50/95) Installing file (5.32-r0)
(51/95) Installing binutils (2.30-r5)
(52/95) Installing gmp (6.1.2-r1)
(53/95) Installing isl (0.18-r0)
(54/95) Installing libgomp (6.4.0-r9)
(55/95) Installing libatomic (6.4.0-r9)
(56/95) Installing mpfr3 (3.1.5-r1)
(57/95) Installing mpc1 (1.0.3-r1)
(58/95) Installing gcc (6.4.0-r9)
(59/95) Installing musl-dev (1.1.19-r10)
(60/95) Installing libc-dev (0.7.1-r0)
(61/95) Installing g++ (6.4.0-r9)
(62/95) Installing make (4.2.1-r2)
(63/95) Installing php7.3-dev (7.3.0-r5)
Executing php7.3-dev-7.3.0-r5.post-install
(64/95) Installing php7.3-dom (7.3.0-r5)
(65/95) Installing php7.3-fpm (7.3.0-r5)
Executing php7.3-fpm-7.3.0-r5.pre-install
Executing php7.3-fpm-7.3.0-r5.post-install
(66/95) Installing gnu-libiconv (1.15-r100)
(67/95) Installing php7.3-iconv (7.3.0-r5)
(68/95) Installing icu-libs (60.2-r2)
(69/95) Installing php7.3-intl (7.3.0-r5)
(70/95) Installing php7.3-opcache (7.3.0-r5)
(71/95) Installing php7.3-pcntl (7.3.0-r5)
(72/95) Installing php7.3-pdo (7.3.0-r5)
(73/95) Installing php7.3-mysqlnd (7.3.0-r5)
(74/95) Installing php7.3-pdo_mysql (7.3.0-r5)
(75/95) Installing php7.3-posix (7.3.0-r5)
(76/95) Installing php7.3-session (7.3.0-r5)
(77/95) Installing php7.3-redis (4.1.1-r0)
(78/95) Installing php7.3-shmop (7.3.0-r5)
(79/95) Installing php7.3-simplexml (7.3.0-r5)
(80/95) Installing libsodium (1.0.16-r0)
(81/95) Installing php7.3-sodium (7.3.0-r5)
(82/95) Installing php7.3-tokenizer (7.3.0-r5)
(83/95) Installing php7.3-xmlwriter (7.3.0-r5)
(84/95) Installing libintl (0.19.8.1-r2)
(85/95) Installing libproc (3.3.15-r0)
(86/95) Installing procps (3.3.15-r0)
(87/95) Installing libffi (3.2.1-r4)
(88/95) Installing gdbm (1.13-r1)
(89/95) Installing readline (7.0.003-r0)
(90/95) Installing sqlite-libs (3.24.0-r0)
(91/95) Installing python2 (2.7.15-r1)
(92/95) Installing py-meld3 (1.0.2-r1)
(93/95) Installing py-setuptools (39.1.0-r0)
(94/95) Installing supervisor (3.3.4-r1)
(95/95) Installing wget (1.19.5-r0)
Executing busybox-1.28.4-r1.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 342 MiB in 108 packages
Removing intermediate container 4084c5088879
 ---> 43589c9c3aeb
Step 4/5 : EXPOSE 9000
 ---> Running in 2a5c66cb96cd
Removing intermediate container 2a5c66cb96cd
 ---> 53d5f47d2157
Step 5/5 : CMD ["php-fpm"]
 ---> Running in b5baefa89b9a
Removing intermediate container b5baefa89b9a
 ---> 422ca2e57731
Successfully built 422ca2e57731
Successfully tagged deleteme:latest
```

> docker run --rm -it deleteme

```
[15-Oct-2018 17:46:33] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/lib/php/7.3/modules/redis (Error loading shared library /usr/lib/php/7.3/modules/redis: No such file or directory), /usr/lib/php/7.3/modules/redis.so (Error relocating /usr/lib/php/7.3/modules/redis.so: _zval_ptr_dtor: symbol not found)) in Unknown on line 0
```

**Comment by petk** [comment]
I see. Then we'll need to rebuild the Redis extension. Currently there has been [4.2.0RC1](https://pecl.php.net/package/redis/4.2.0RC1) released...

**Comment by PhilETaylor** [comment]
Im using 4.2.0RC1 in production at myJoomla.com with no issues - built from source instead of your package.

**Comment by petk** [comment]
Redis 4.2.0RC1 has been added to these repos as well now...

**Comment by PhilETaylor** [comment]
> docker build . --no-cache --tag deleteme

```
<snip>
Successfully tagged deleteme:latest
~/test docker run --rm -it deleteme
~/test docker run --rm -it deleteme php -v
PHP 7.3.0RC3 (cli) (built: Oct 11 2018 11:20:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0RC3, Copyright (c) 1999-2018, by Zend Technologies
~/test docker run --rm -it deleteme php -i | grep redis
/etc/php/7.3/conf.d/redis.ini
redis
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000
redis.session.locking_enabled => 0 => 0
Registered save handlers => files user redis rediscluster
This program is free software; you can redistribute it and/or modify
```

Confirmed fixed - thanks again!
